workflows:
  react-native-ios:
    name: ITC TKB iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      vars:
        XCODE_WORKSPACE: "ios/ITCTKB.xcworkspace"
        XCODE_SCHEME: "ITCTKB"
        BUNDLE_ID: "com.hoangkiet.itctkb"
      node: 20
      xcode: latest
      cocoapods: default

    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $CM_BUILD_DIR/node_modules

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true

    scripts:
      - name: Check environment
        script: |
          cd ITCTKB-ReactNative
          npm install
          echo "=== Environment Check ==="
          pwd
          echo "--- Files in current directory ---"
          ls -la
          echo "--- Node version ---"
          node --version
          echo "--- NPM version ---"
          npm --version
          echo "--- NPM config ---"
          npm config list
          
      - name: Install dependencies
        script: npm install --legacy-peer-deps

      - name: Install Expo CLI
        script: |
          npm install -g eas-cli @expo/cli

      - name: Prebuild Expo project
        script: |
          npx expo prebuild --platform ios --clean

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update

      - name: Build ipa for distribution (without code signing)
        script: |
          cd ios
          xcodebuild \
            -workspace ITCTKB.xcworkspace \
            -scheme ITCTKB \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build/ITCTKB.xcarchive \
            archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/build/ITCTKB.xcarchive \
            -exportPath $CM_BUILD_DIR/build/ios/ipa \
            -exportOptionsPlist exportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - build/*.xcarchive

    publishing:
      email:
        recipients:
          - hoangkiet@icloud.com
        notify:
          success: true
          failure: true
